// <auto-generated />
using System;
using GestaoPredio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoPredio.Infrastructure.Persistence.Migrations.PostgreSql
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907142242_ProfessionalDescription")]
    partial class ProfessionalDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoPredio.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ChangedFields")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Action", "OccurredAt");

                    b.HasIndex("TargetEntityType", "TargetEntityId", "OccurredAt")
                        .HasDatabaseName("IX_AuditEntries_TargetEntity");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("GestaoPredio.Domain.Availability.OperatingHourInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId", "DayOfWeek", "OpensAt")
                        .IsUnique()
                        .HasDatabaseName("UX_OperatingHourIntervals_Schedule_Day_Open");

                    b.ToTable("OperatingHourIntervals", null, t =>
                        {
                            t.HasCheckConstraint("CK_OperatingHourIntervals_DayOfWeek", "\"DayOfWeek\" BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_OperatingHourIntervals_Period", "\"ClosesAt\" > \"OpensAt\"");
                        });
                });

            modelBuilder.Entity("GestaoPredio.Domain.Availability.OperatingHoursSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("OperatingHoursSchedules", (string)null);
                });

            modelBuilder.Entity("GestaoPredio.Domain.Availability.RoomBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "EndAt")
                        .HasDatabaseName("IX_RoomBlocks_Room_End");

                    b.HasIndex("RoomId", "Status", "StartAt")
                        .HasDatabaseName("IX_RoomBlocks_Room_Status_Start");

                    b.ToTable("RoomBlocks", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoomBlocks_Period", "\"EndAt\" > \"StartAt\"");

                            t.HasCheckConstraint("CK_RoomBlocks_Status", "\"Status\" IN ('ACTIVE', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("GestaoPredio.Domain.Customers.CheckInToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("UX_CheckInTokens_ReservationId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_CheckInTokens_TokenHash");

                    b.ToTable("CheckInTokens", (string)null);
                });

            modelBuilder.Entity("GestaoPredio.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedPhone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Customers_ApplicationUserId")
                        .HasFilter("\"ApplicationUserId\" IS NOT NULL");

                    b.HasIndex("NormalizedPhone")
                        .IsUnique()
                        .HasDatabaseName("UX_Customers_NormalizedPhone");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("GestaoPredio.Domain.Files.PrivateFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_PrivateFiles_StorageKey");

                    b.ToTable("PrivateFiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_PrivateFiles_Length_Positive", "\"Length\" > 0");

                            t.HasCheckConstraint("CK_PrivateFiles_Purpose", "\"Purpose\" = 'PROFESSIONAL_PHOTO'");
                        });
                });

            modelBuilder.Entity("GestaoPredio.Domain.Finance.FinancialCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdjustmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("CalculatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CalculationDetails")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReferencePeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReferencePeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LeaseId")
                        .HasDatabaseName("IX_FinancialCharges_LeaseId");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("IX_FinancialCharges_ProfessionalId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FinancialCharges_TenantId");

                    b.HasIndex("ReferencePeriodStart", "ReferencePeriodEnd")
                        .HasDatabaseName("IX_FinancialCharges_Period");

                    b.HasIndex("Status", "DueDate")
                        .HasDatabaseName("IX_FinancialCharges_Status_DueDate");

                    b.HasIndex("LeaseId", "ReferencePeriodStart", "ReferencePeriodEnd")
                        .IsUnique()
                        .HasDatabaseName("UX_FinancialCharges_Lease_Period");

                    b.ToTable("FinancialCharges", null, t =>
                        {
                            t.HasCheckConstraint("CK_FinancialCharges_Amounts", "\"CalculatedAmount\" >= 0 AND \"FinalAmount\" >= 0");

                            t.HasCheckConstraint("CK_FinancialCharges_Period", "\"ReferencePeriodEnd\" > \"ReferencePeriodStart\"");

                            t.HasCheckConstraint("CK_FinancialCharges_Status", "\"Status\" IN ('PENDING', 'PAID', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("GestaoPredio.Domain.Leases.Lease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short?>("BillingDueDay")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("BillingStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ContractedRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("MaterializedThroughAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<short?>("MonthlyAnchorDay")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("OccupancyEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccupancyStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalId", "LifecycleState", "OccupancyStartAt")
                        .HasDatabaseName("IX_Leases_Professional_State_Start");

                    b.HasIndex("RoomId", "LifecycleState", "OccupancyStartAt")
                        .HasDatabaseName("IX_Leases_Room_State_Start");

                    b.HasIndex("TenantId", "LifecycleState", "BillingStartAt")
                        .HasDatabaseName("IX_Leases_Tenant_State_Billing");

                    b.ToTable("Leases", null, t =>
                        {
                            t.HasCheckConstraint("CK_Leases_BillingDueDay", "\"BillingDueDay\" IS NULL OR \"BillingDueDay\" BETWEEN 1 AND 31");

                            t.HasCheckConstraint("CK_Leases_ContractedRate", "\"ContractedRate\" >= 0");

                            t.HasCheckConstraint("CK_Leases_DatesAndMode", "\"BillingStartAt\" <= \"OccupancyStartAt\" AND (\"OccupancyEndAt\" IS NULL OR \"OccupancyEndAt\" > \"OccupancyStartAt\") AND ((\"Mode\" = 'MONTHLY' AND \"MonthlyAnchorDay\" BETWEEN 1 AND 31) OR (\"Mode\" IN ('DAILY', 'HOURLY') AND \"OccupancyEndAt\" IS NOT NULL AND \"MonthlyAnchorDay\" IS NULL))");

                            t.HasCheckConstraint("CK_Leases_LifecycleState", "\"LifecycleState\" IN ('OPEN', 'ENDING_PENDING', 'ENDED', 'CANCELLED')");

                            t.HasCheckConstraint("CK_Leases_Mode", "\"Mode\" IN ('MONTHLY', 'DAILY', 'HOURLY')");
                        });
                });

            modelBuilder.Entity("GestaoPredio.Domain.Leases.LeaseOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LeaseId", "StartAt")
                        .IsUnique()
                        .HasDatabaseName("UX_LeaseOccurrences_LeaseId_StartAt");

                    b.ToTable("LeaseOccurrences", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaseOccurrences_State", "\"State\" IN ('PLANNED', 'CANCELLED', 'COMPLETED')");
                        });
                });

            modelBuilder.Entity("GestaoPredio.Domain.Professionals.Professional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("NormalizedProfession")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("PhotoFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Professionals_ApplicationUserId");

                    b.HasIndex("PhotoFileId")
                        .IsUnique()
                        .HasDatabaseName("UX_Professionals_PhotoFileId");

                    b.ToTable("Professionals", (string)null);
                });

            modelBuilder.Entity("GestaoPredio.Domain.Reservations.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("OriginalReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Reservations_CustomerId");

                    b.HasIndex("OriginalReservationId")
                        .HasDatabaseName("IX_Reservations_OriginalReservationId");

                    b.HasIndex("ProfessionalId", "Status", "StartAt")
                        .HasDatabaseName("IX_Reservations_Professional_Status_Start");

                    b.HasIndex("RoomId", "Status", "StartAt")
                        .HasDatabaseName("IX_Reservations_Room_Status_Start");

                    b.ToTable("Reservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reservations_Kind", "\"Kind\" IN ('NEW', 'RESCHEDULE', 'CANCELLATION')");

                            t.HasCheckConstraint("CK_Reservations_Period", "\"EndAt\" > \"StartAt\"");

                            t.HasCheckConstraint("CK_Reservations_RejectionReason", "\"Status\" <> 'REJECTED' OR \"RejectionReason\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Reservations_Status", "\"Status\" IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("GestaoPredio.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_Rooms_NormalizedName");

                    b.ToTable("Rooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rooms_DailyRate_NonNegative", "\"DailyRate\" >= 0");

                            t.HasCheckConstraint("CK_Rooms_HourlyRate_NonNegative", "\"HourlyRate\" >= 0");
                        });
                });

            modelBuilder.Entity("GestaoPredio.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName", "Id")
                        .HasDatabaseName("IX_Tenants_NormalizedName");

                    b.ToTable("Tenants", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tenants_Kind", "\"Kind\" IN ('INDIVIDUAL', 'LEGAL_ENTITY')");
                        });
                });

            modelBuilder.Entity("GestaoPredio.Domain.Visits.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ArrivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ServiceStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Visits_CustomerId");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("IX_Visits_ReservationId");

                    b.HasIndex("Status", "ArrivedAt")
                        .HasDatabaseName("IX_Visits_Status_ArrivedAt");

                    b.HasIndex("ProfessionalId", "Status", "ArrivedAt")
                        .HasDatabaseName("IX_Visits_Professional_Status_ArrivedAt");

                    b.HasIndex("RoomId", "Status", "ArrivedAt")
                        .HasDatabaseName("IX_Visits_Room_Status_ArrivedAt");

                    b.ToTable("Visits", null, t =>
                        {
                            t.HasCheckConstraint("CK_Visits_StateTimestamps", "(\"Status\" = 'WAITING' AND \"ServiceStartedAt\" IS NULL AND \"EndedAt\" IS NULL AND \"CancelledAt\" IS NULL)\r\nOR (\"Status\" = 'IN_SERVICE' AND \"ServiceStartedAt\" IS NOT NULL AND \"EndedAt\" IS NULL AND \"CancelledAt\" IS NULL)\r\nOR (\"Status\" = 'ENDED' AND \"ServiceStartedAt\" IS NOT NULL AND \"EndedAt\" IS NOT NULL AND \"CancelledAt\" IS NULL)\r\nOR (\"Status\" = 'CANCELLED' AND \"EndedAt\" IS NULL AND \"CancelledAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Visits_Status", "\"Status\" IN ('WAITING', 'IN_SERVICE', 'ENDED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("GestaoPredio.Domain.Visits.VisitTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsCorrection")
                        .HasColumnType("boolean");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitId", "OccurredAt")
                        .HasDatabaseName("IX_VisitTransitions_Visit_OccurredAt");

                    b.ToTable("VisitTransitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_VisitTransitions_CorrectionReason", "NOT \"IsCorrection\" OR \"Reason\" IS NOT NULL");

                            t.HasCheckConstraint("CK_VisitTransitions_NewStatus", "\"NewStatus\" IN ('WAITING', 'IN_SERVICE', 'ENDED', 'CANCELLED')");

                            t.HasCheckConstraint("CK_VisitTransitions_PreviousStatus", "\"PreviousStatus\" IS NULL OR \"PreviousStatus\" IN ('WAITING', 'IN_SERVICE', 'ENDED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("GestaoPredio.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GestaoPredio.Domain.Availability.OperatingHourInterval", b =>
                {
                    b.HasOne("GestaoPredio.Domain.Availability.OperatingHoursSchedule", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoPredio.Domain.Availability.RoomBlock", b =>
                {
                    b.HasOne("GestaoPredio.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoPredio.Domain.Customers.CheckInToken", b =>
                {
                    b.HasOne("GestaoPredio.Domain.Reservations.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoPredio.Domain.Customers.Customer", b =>
                {
                    b.HasOne("GestaoPredio.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("GestaoPredio.Domain.Finance.FinancialCharge", b =>
                {
                    b.HasOne("GestaoPredio.Domain.Leases.Lease", null)
                        .WithMany()
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestaoPredio.Domain.Professionals.Professional", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestaoPredio.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoPredio.Domain.Leases.Lease", b =>
                {
                    b.HasOne("GestaoPredio.Domain.Professionals.Professional", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestaoPredio.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestaoPredio.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoPredio.Domain.Leases.LeaseOccurrence", b =>
                {
                    b.HasOne("GestaoPredio.Domain.Leases.Lease", null)
                        .WithMany()
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoPredio.Domain.Professionals.Professional", b =>
                {
                    b.HasOne("GestaoPredio.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GestaoPredio.Domain.Files.PrivateFile", null)
                        .WithMany()
                        .HasForeignKey("PhotoFileId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("GestaoPredio.Domain.Reservations.Reservation", b =>
                {
                    b.HasOne("GestaoPredio.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GestaoPredio.Domain.Reservations.Reservation", null)
                        .WithMany()
                        .HasForeignKey("OriginalReservationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GestaoPredio.Domain.Professionals.Professional", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestaoPredio.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoPredio.Domain.Visits.Visit", b =>
                {
                    b.HasOne("GestaoPredio.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GestaoPredio.Domain.Professionals.Professional", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestaoPredio.Domain.Reservations.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GestaoPredio.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("GestaoPredio.Domain.Visits.VisitTransition", b =>
                {
                    b.HasOne("GestaoPredio.Domain.Visits.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GestaoPredio.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GestaoPredio.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPredio.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GestaoPredio.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
